### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by vcanilkumar** [SAP-samples/hana-developer-cli-tool-example#10]
Hi Team,

trying to connect  to CF service using below command 
hana-cli serviceKey <<Service Instance Name>> default

Connection failed (RTE:[89006] System call 'connect' failed, rc=10061:No connection could be made because the target machine actively refused it

Regards,
Anil

**Comment by jung-thomas** [comment]
Can you give me some details about what kind of environment you are doing this in - CF or XS?  Are you logged into cf/xs from the command line before you issue this command?  Is the command creating the default-env.json and then just failing on the connection? If so can you look at and maybe post the contents (with passwords or certificate of course) some of the details in the default-env.json.

**Comment by vcanilkumar** [comment]
Thanks Thomas for your response.

- I'm using CF , logged in to CF using command line .
- Command is not creating default-env.json and just failing saying connection refused.

May be I will try creating the default-env.json manually and verify.

Rgeards,
Anil

**Comment by vcanilkumar** [comment]
I have maintained the default-env.json.
The command "hana-cli status" is giving error "No service matches hana"
Image of my service instances attached.

![image](https://user-images.githubusercontent.com/11570020/89974530-f73b3a80-dc80-11ea-852a-bdc015c2b5d5.png)

**Comment by jung-thomas** [comment]
Did you create the content in the default-env.json manually?  That error would indicate that the tag is missing from the service entry in the default-env.json or the file is completely empty or not structured correctly.  Have you just tried to use the hana-cli connect to build the default-env.json via the prompts?

**Comment by jung-thomas** [comment]
Discussed via email and resolved.
