### ISSUE TITLE
Export to sqlite does not work

### ISSUE THREAD

**Issue by vybiralpetr** [SAP-samples/hana-developer-cli-tool-example#102]
Hello,
I am trying to export our tables to sqlite, but I am getting an error:
```
CDS compilation failed
Error: sqlDialect “sqlite” can't be combined with sqlMapping ‘quoted’
```

I think that the problem might be in this [line](https://github.com/SAP-samples/hana-developer-cli-tool-example/blob/7f1a7a4736cfd647d1227ced2909ea97fc766d00/bin/inspectTable.js#L134) of code:

I tried to export both table and view.
```
hana-cli inspectTable -t "XYZ" -o sqlite
hana-cli inspectView -v "XYZ" -o sqlite
```

**Comment by jung-thomas** [comment]
Looks like quoted isn't supported any longer in the cds compile to sqlite. I removed that option.  Issue is fixed in new version 3.202302.4.
