### ISSUE TITLE
massconvert for hdbtabletype

### ISSUE THREAD

**Issue by karthicktsb** [SAP-samples/hana-developer-cli-tool-example#104]
Hi Jung,

Do you plan to support massConvert from hdbdd (Type) to hdbtable or hdbtabletype.

For example:

context GLOBAL {

	type AUDIT {
		CREATED: UTCTimestamp;
		CREATEDBY: Integer64;
		CHANGED: UTCTimestamp;
		CHANGEDBY: Integer64;
	};
	
	entity TTO{
		key PO_TYPE: String(32);
		PRIO: Integer;
	};
};

During massconvert, "entity" is converted but not the "type". I have around 100 such types needs to be converted to hdbtable or hdbtabletype.

Do you able to take this enhancement request?

Regards,
Karthick

**Comment by jung-thomas** [comment]
I'm afraid that wouldn't be in the scope of this tool.  We read the SQL/runtime definition of the object (regardless of origin/design time type) and then convert that to a new target.  But what you are describing would require input of the existing hdbdd and processing it directly.

**Comment by jung-thomas** [comment]
Looks like the issue here is just the :: in the original object name which isn’t valid in CAP CDS. You can use the noColons option to replace those with a period instead

Replace :: in table/view path with
                                           dot        [boolean] [default: false]

**Comment by karthicktsb** [comment]
Thanks but still it is returning the same error and program hasn't terminate. 

hana-cli inspectTable -s HFP_INTERNAL -t HFP_PMT.TABLE::GLOBAL.AUDIT -o hdbtable -a --noColons
Using Connection Configuration loaded via default-env-admin.json

CDS compilation failed
<stdin>.cds:1:22-23: Error: Extraneous ‘:’, expecting ‹Identifier›
<stdin>.cds:1:23-35: Error: No artifact has been found with name “GLOBAL_AUDIT” (in entity:“HFP_PMT_TABLE”)

And my main request is do you able to support this massConvert also ?

**Comment by jung-thomas** [comment]
You need to add “true” after noColons

**Comment by karthicktsb** [comment]
Sorry to trouble you again, I am unable to see any effect of using --noColons true in the command.
output CDS generates cds file with ::.

hana-cli inspectTable -s HFP_INTERNAL -t HFP_PMT.TABLE::GLOBAL.AUDIT --noColons true -a -o hdbtable --hana
Using Connection Configuration loaded via default-env-admin.json

CDS compilation failed
<stdin>.cds:1:22-23: Error: Extraneous ‘:’, expecting ‹Identifier›
<stdin>.cds:1:23-35: Error: No artifact has been found with name “GLOBAL_AUDIT” (in entity:“HFP_PMT_TABLE”)
^C
C:\Users\I312836>hana-cli inspectTable -s HFP_INTERNAL -t HFP_PMT.TABLE::GLOBAL.AUDIT --noColons true -a -o cds --hana
Using Connection Configuration loaded via default-env-admin.json

@cds.persistence.exists
Entity HFP_PMT_TABLE::GLOBAL_AUDIT {
        CREATED: Timestamp  @title: 'CREATED' ;
        CREATEDBY: Integer64  @title: 'CREATEDBY' ;
        CHANGED: Timestamp  @title: 'CHANGED' ;
        CHANGEDBY: Integer64  @title: 'CHANGEDBY' ;
}

**Comment by jung-thomas** [comment]
You said you wanted to do the massConvert.  The noColons option is in the massConvert command. https://github.com/SAP-samples/hana-developer-cli-tool-example#massconvert

**Comment by jung-thomas** [comment]
Just published a new version with two things that should help. I added the noColons option to inspectTable:
![image](https://user-images.githubusercontent.com/12159356/224824557-28667953-41eb-49aa-995f-3a3408ac06d9.png)

And the massConvert command will now find user defined types (Table Types):
![image](https://user-images.githubusercontent.com/12159356/224824634-dced7eb1-51b2-4b4e-a851-ec52698709fc.png)
