### ISSUE TITLE
hana-cli massConvert Boolean field with default 

### ISSUE THREAD

**Issue by ravindraP20** [SAP-samples/hana-developer-cli-tool-example#110]
Hello Team,

I have used the hana-cli massConvert command to convert the table defined in .hdbcds to .hdbtable artifact.
There is one issue with the Boolean type field.
In my .hdbcds the Boolean field has default false but the massConver command converts it to DEFAULT '0' which is not a Boolean value.

 SingleClient      : Boolean default false; is converted to "SingleClient" BOOLEAN DEFAULT '0',

It is expected that it should convert it to BOOLEAN DEFAULT false or BOOLEAN DEFAULT true.

Thanks,
Ravindra

**Comment by jung-thomas** [comment]
Can you please let me know what options in the massConvert command you are using?  

I have feeling this might be due to the following:
_When the client does not support a boolean type, it returns 1 for TRUE and 0 for FALSE._

**Comment by jung-thomas** [comment]
I think I have all the scenarios covered and tested with the Boolean. The metadata returned from the HANA Columns view does bring back 0 or 1.  I added some logic to convert  that back to true/false when the target output of the conversion is cds based.   New version is pushed to npm. Let me know if that doesn't fix your situation.

**Comment by ravindraP20** [comment]
Thank for quick reply and fix.
It has solved my issue.
