### ISSUE TITLE
Check that Container Name passed to createContainer is an uppercase String without -

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/hana-developer-cli-tool-example#111]
Hi Thomas,

after quite some time I'm using the hana-cli again. Thank you for the great work you've done here. 

I've used the createContainer command on my HANA Express Edition. But I only got `RETURN_CODE  0` when I've used all uppercase characters and no -. Otherwise I've got this:

```
hana-cli createContainer TEST-CONTAINER -a
Using Connection Configuration loaded via default-env-admin.json 

key          value
-----------  -----
RETURN_CODE  -1   
REQUEST_ID   68  
```

Even when the RETURN_CODE was -1 still a default-env.json was created. I would suggest to either check the RETURN_CODE or the input. 

Best Regards
Gregor

**Comment by jung-thomas** [comment]
Will have a look at it later this week. I have some work in progress to update the tool to include CAP 7.0 features and support. Will try and address this issue in the release update.

**Comment by jung-thomas** [comment]
Took me too long to get back to this one, but updated now.  I correct some common errors (like converting name to upper case automatically.  And report errors for other illegal characters. I used this list here for user names https://help.sap.com/docs/SAP_HANA_PLATFORM/b3ee5778bc2e4a089d3299b82ec762a7/55d3b5a01166494582cc12f70ccfa17f.html
But I'm about 99% sure the same applies for container and group names.  Hopefully I've not checked too aggressively.

**Comment by gregorwolf** [comment]
Thank you.
