### ISSUE TITLE
Hana calculation view with parameters

### ISSUE THREAD

**Issue by dbizien** [SAP-samples/hana-developer-cli-tool-example#112]
Hi, 

First of all thank you for this tool, it is really great.
I'm using it really often in order to have the cds definition of calculationview.
ex: hana-cli inspectView "AGORA_BI_GOBI_1" "CUBE_GED_REPLICATION_RAPPORTSTO_V" -o cds

In a specific case, I have a calculation view with parameters and I would like to have the definition with the parameters.
I would like to publish it with parameters as it seems it is now possible. ( https://cap.cloud.sap/docs/advanced/hana#views-with-parameters ).
hana-cli seems to generate the cds definition without the parameters. 
Is there an option to generate with parameters ?

Thanks,
David.

**Comment by jung-thomas** [comment]
There is already an open issue on adding parameters - part of the original request to add Calculation View support. #83
