### ISSUE TITLE
massConvert command is not working for table names with lower case letters

### ISSUE THREAD

**Issue by sucheno** [SAP-samples/hana-developer-cli-tool-example#12]
Hi @jung-thomas ,

I am not able to make "massConvert" command work for tables with case sensitive names or lowercase letters.
Default option for tables which is "*" also is not working in this scenario. It is working perfectly fine for table names with upper case letters only.
I have hundreds of tables in different schemas with lowercase and case sensitive naming which are created by ._hdbdd_ files.
Can you help me to figure out the solution? 

Command used:   
`hana-cli massConvert -a -s "SCHEMANAME" -o "hdbtable"`

Error is:  
```
Schema: SCHEMANAME, Table: *
{ code: 397,
  message:
   'invalid object name: SCHEMANAME.COM.MYCOMPANY.DB::VENDORS has an unknown type.',
  sqlState: 'HY000' }
TypeError: Cannot read property 'stop' of undefined
    at process.errorHandler (C:\Users\SUCHEN\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\bin\cli.js:14:22)
    at process.emit (events.js:198:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
C:\Users\SUCHEN\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\bin\cli.js:14
    global.__spinner.stop()
```
Thanks.

**Comment by jung-thomas** [comment]
@sucheno - thanks for reporting this issue. I've just committed a fix for this issue. I've pushed to NPM. Version 1.202009.1 and higher will contain this fix.
