### ISSUE TITLE
Unsupported type when exporting CDS of calculation view with parameters

### ISSUE THREAD

**Issue by lorenzofratus** [SAP-samples/hana-developer-cli-tool-example#120]
Hi Thomas,

I need to export the CDS definition of a calculation view with parameters. 
I tried to use both `massConvert` and `inspectView` commands and I got the same problem.

One of the parameters is defined in the calculation view editor as type `DATE` (see the screenshot below) but when I convert it into CAP I get the `**UNSUPPORTED TYPE - DAYDATE` token instead of the actual type.

![unnamed](https://github.com/SAP-samples/hana-developer-cli-tool-example/assets/61735268/f74f28bb-66be-4c6b-a4dc-1bd4c5e48126)

I saw from other closed issues that this behavior is expected when using HANA specific types but in this case I feel like it might be a bug since `DAYDATE` and `DATE` are synonyms ([link to the documentation](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/3f81ccc7e35d44cbbc595c7d552c202a.html)).

Another odd thing that makes me think of a bug is that the same calculation view has a field of type `DATE` that is exported correctly.

I tried using the `--hana` and `--useHanaTypes` options but nothing changed.

Thanks for any help you can give me!

**Comment by jung-thomas** [comment]
There was no type cross reference mapping for DAYDATE. I've added it and pushed a new version.
