### ISSUE TITLE
Error message invalid name of function or procedure: no procedure with name CREATE_CONTAINER found

### ISSUE THREAD

**Issue by tometzki** [SAP-samples/hana-developer-cli-tool-example#14]
Hello,

i am working on the first video ( https://www.youtube.com/watch?v=FWOo_mm0sfQ )  and i try with hana-cli createContainer to create a Container on a hana cloud. You do the tasks with a local hana database but i didnt have anyone. 
But i got this message:
Isnt possible to do the same tasks with a hana cloud ? hana-cli connect was successfully.

[damian@centos db]$ hana-cli createContainer
Input: Container Name:  BOOKSHOP
Input: Encrypt connections (required for HANA As A Service or HANA Cloud):  t
⠦ 
{
  code: 328,
  message: 'invalid name of function or procedure: no procedure with name CREATE_CONTAINER found: line 1 col 14 (at pos 13)',
  sqlState: 'HY000'
[damian@centos db]$

**Comment by jung-thomas** [comment]
Unfortunately the HANA Cloud version doesn't support the createContainer command. Really the createContainer command in hana-cli was designed for HANA standalone DB which contains no XSA or CF layer.  In HANA Cloud you always have the CF layer, so there is really no value in going to the HDI stored procedures directly.  I should probably add some documentation or check to the effect.

However in HANA Cloud since you always have the CF layer,  I would suggest using the cf command line or SCP Cockpit to create the HDI container. For instance just with cf create-container/cf create-service-key command.  Then use the hana-cli serviceKey command. This will read the HDI container connection information via the cf command line and write the results into a default-env.json for you to use.  
https://github.com/SAP-samples/hana-developer-cli-tool-example#servicekey

For an example of this usage see: https://www.youtube.com/watch?v=t3nIXxibmso&t=1730s

**Comment by tometzki** [comment]
Many thanks it works. hana-cli status output is now positiv ! Great !
One question is it possible the cf binary  to build on a local maschine ?

**Comment by jung-thomas** [comment]
>One question is it possible the cf binary to build on a local maschine ?
Not sure what you mean by that.  You want to install CF CLI locally.
https://docs.cloudfoundry.org/cf-cli/install-go-cli.html
https://github.com/cloudfoundry/cli
https://tools.hana.ondemand.com/#cloud

 Or actually build the CF CLI from sources?
https://github.com/cloudfoundry/cli/blob/master/.github/CONTRIBUTING.md#building-the-cf-binary

**Comment by tometzki** [comment]
Hello,

Many thanks. Yes that is what i search. 
What i see the files for the bookshop are different in video. For example my package.json isnt the same

{
    "name": "bookshop",
    "version": "1.0.0",
    "description": "A simple CAP project.",
    "repository": "<Add your repository here>",
    "license": "UNLICENSED",
    "private": true,
    "dependencies": {
        "@sap/cds": "^4",
        "express": "^4",
        "@sap/hana-client": "^2.4.177"
    },
    "devDependencies": {
        "sqlite3": "^5"
    },
    "scripts": {
        "start": "npx cds run"
    },
    "cds": {
        "requires": {
            "db": {
                "kind": "sql"
            }
        }
    }
}

**Comment by jung-thomas** [comment]
Nothing to be alarmed about there.  I recorded the video you reference back in February and since then CAP has had several updates include a major new version back in August.  So the fact that the version numbers are different is correct.

**Comment by tometzki** [comment]
OK then my last question, i hope. 
CDS build ignores my schema.cds in the db folder. 
I do not get an error message. 
And then npm install run without error but npm start didnt work. 

And i dont know what i do wrong. 

Many thanks for you help and time


Best regards
Damian

**Comment by tometzki** [comment]
Hello Thomas,

now i found out what the reason was for my problems. The File **package.json** under the db folder was missing. 

Which step create this file in the process ?

**Comment by tometzki** [comment]
Good morning,
i see every time i build a new project and create a small schema.cds. The will be ignored when i run cds build.

**Comment by jung-thomas** [comment]
Yes I think your package.json lacks the hana configuration. Maybe have a look at the example here: https://github.com/SAP-samples/hana-opensap-cloud-2020/blob/main/package.json#L60

**Comment by tometzki** [comment]
Hello Thomas,

i have written a short documentation for the build: 
cds init <project> --add <params>
cd <project>
create <file>.cds and place in db folder
#Run in db Folder
  cds build --for hana
  cf create-service hana hdi-shared <name>
  cf create-service-key <name> default
  hana-cli serviceKey <name> default
  npm install
  npm start
And now it works without errors. 

Great :-)
