### ISSUE TITLE
error Verification failed while extracting @sap/hana-client@2.4.202:

### ISSUE THREAD

**Issue by diraschk** [SAP-samples/hana-developer-cli-tool-example#15]
Hi Thomas,

do you have an idea, how we can fix this issue:
**_error Verification failed while extracting @sap/hana-client@2.4.202_**

This is a new issue for our long existing db-modul, when we try to build it in a new space with our WebIDE.
We never had this issue in the past. But after playing with the hana-client for local developments (with VSC)  some weeks ago, I came now across to this issue while building our db-modul.

1. Checked the project. Couldn't find any reference to the hana-client. Don't where this comes from...

2. removed the devx-npm-cache-fs
xs unbind-service di-local-npm-registry devx-npm-cache-fs
xs delete-service devx-npm-cache-fs 
xs create-service fs-storage free devx-npm-cache-fs
xs bind-service  di-local-npm-registry devx-npm-cache-fs
xs restage di-local-npm-registry
xs restart di-local-npm-registry 
 
3. Already existing projects with the same db-modul don't have this issue.

`316 warn tarball tarball data for @sap/hana-client@2.4.202 (sha512-SLAXY230hcI7QpksnYUzYEyghyzlZYs0/5K8HzdVYNE2oGf4Z4XN8Zm8cIeQ5LCGyB27apsmSjMZ0tE+z2HrZw==) seems to be corrupted. Trying one more time.
317 warn tarball tarball data for @sap/hana-client@2.4.202 (sha512-SLAXY230hcI7QpksnYUzYEyghyzlZYs0/5K8HzdVYNE2oGf4Z4XN8Zm8cIeQ5LCGyB27apsmSjMZ0tE+z2HrZw==) seems to be corrupted. Trying one more time.
318 timing action:extract Completed in 7771ms
319 verbose unlock done using /hana/shared/TBD/xs/app_working/tbase-dev/executionroot/313656e1-5a46-4199-b24f-7170c27408f6/app/META-INF/cache/node8.15/.npm/_locks/staging-3afc96fa8c407585.lock for /hana/shared/TBD/xs/app_working/tbase-dev/executionroot/313656e1-5a46-4199-b24f-7170c27408f6/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-3773557706351202928/db/node_modules/.staging
320 timing stage:rollbackFailedOptional Completed in 0ms
321 timing stage:runTopLevelLifecycles Completed in 8335ms
322 silly saveTree deploy@
322 silly saveTree `-- @sap/hdi-deploy@3.11.15
322 silly saveTree   +-- @sap/hana-client@2.4.202
322 silly saveTree   | `-- debug@3.1.0
322 silly saveTree   |   `-- ms@2.0.0
322 silly saveTree   +-- @sap/hdi@2.2.7
322 silly saveTree   | `-- async@3.1.0
322 silly saveTree   +-- @sap/xsenv@2.2.0
322 silly saveTree   | +-- debug@3.1.0
322 silly saveTree   | | `-- ms@2.0.0
322 silly saveTree   | `-- verror@1.10.0
322 silly saveTree   |   +-- assert-plus@1.0.0
322 silly saveTree   |   +-- core-util-is@1.0.2
322 silly saveTree   |   `-- extsprintf@1.4.0
322 silly saveTree   +-- async@3.1.0
322 silly saveTree   `-- handlebars@4.7.6
322 silly saveTree     +-- minimist@1.2.5
322 silly saveTree     +-- neo-async@2.6.2
322 silly saveTree     +-- source-map@0.6.1
322 silly saveTree     +-- uglify-js@3.11.4
322 silly saveTree     `-- wordwrap@1.0.0
323 warn deploy@ No description
324 warn deploy@ No repository field.

325 warn deploy@ No license field.
326 verbose stack Error: sha512-SLAXY230hcI7QpksnYUzYEyghyzlZYs0/5K8HzdVYNE2oGf4Z4XN8Zm8cIeQ5LCGyB27apsmSjMZ0tE+z2HrZw== integrity checksum failed when using sha512: wanted sha512-SLAXY230hcI7QpksnYUzYEyghyzlZYs0/5K8HzdVYNE2oGf4Z4XN8Zm8cIeQ5LCGyB27apsmSjMZ0tE+z2HrZw== but got sha512-HPVCHKnghU2t9ni6Eut0iwNMVqPIcJlTPe/QtRSgtc4ZBlAXrSbOD4CmztfSQa0o7Pinu3UyQX9EpoX4G7/+8A==. (53837145 bytes)
326 verbose stack     at Transform.on (/hana/shared/TBD/xs/app_working/tbase-dev/executionroot/313656e1-5a46-4199-b24f-7170c27408f6/app/META-INF/resources/nodejs/vendor/node8.15/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
326 verbose stack     at emitNone (events.js:111:20)
326 verbose stack     at Transform.emit (events.js:208:7)
326 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
326 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
326 verbose stack     at process._tickCallback (internal/process/next_tick.js:181:9)
327 verbose cwd /hana/shared/TBD/xs/app_working/tbase-dev/executionroot/313656e1-5a46-4199-b24f-7170c27408f6/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-3773557706351202928/db
328 verbose Linux 4.12.14-150.17-default
329 verbose argv "/hana/shared/TBD/xs/app_working/tbase-dev/executionroot/313656e1-5a46-4199-b24f-7170c27408f6/app/META-INF/resources/nodejs/vendor/node8.15/bin/node" "/hana/shared/TBD/xs/app_working/tbase-dev/executionroot/313656e1-5a46-4199-b24f-7170c27408f6/app/META-INF/resources/nodejs/vendor/node8.15/lib/node_modules/npm/bin/npm-cli.js" "install"
330 verbose node v8.15.0
331 verbose npm  v6.4.1
332 error code EINTEGRITY
333 error Verification failed while extracting @sap/hana-client@2.4.202:
333 error Verification failed while extracting @sap/hana-client@2.4.202:`

Best Regards

**Comment by jung-thomas** [comment]
This issue doesn't seem to be related to this project. I'd suggest posting your question on the SAP Community Q&A or enter a support ticket instead.  I will add, have you checked that you npm cache is reconfigured to point to npmjs.com for the SAP upstream link now.  The separate npm.sap.com repository is no longer needed nor maintained.

**Comment by diraschk** [comment]
this is what we use as mentioned in the sap-docu 
- name: di-local-npm-registry
 properties:
 UPSTREAM_LINK: "http://registry.npmjs.org/"
 SAPUPSTREAM_LINK: "https://npm.sap.com"

should we use?
 UPSTREAM_LINK: "http://registry.npmjs.org/"
 SAPUPSTREAM_LINK: ""http://registry.npmjs.org/"

**Comment by jung-thomas** [comment]
>should we use?
Yes. Everything has been moved to the public, standard registry now.

**Comment by diraschk** [comment]
thanks a lot!
