### ISSUE TITLE
Missing guide to connect hana-cli to hana services

### ISSUE THREAD

**Issue by albertlast** [SAP-samples/hana-developer-cli-tool-example#18]
Maybe i'm blind but i didn't finde any guide which information i need to take from which places to be able to connect to my hana cloud trial service.

The host name i found by myself,
to allow connection form any ip checked
found the admin user checked
the port i'm not 100% sure if this is the index service port or something else?
Encrypt connections - you mention in on of you videos that needs to be enabled
hdb user store key - i don't need i guess?
ssl trust store - dunno

so far i get with my guessing game:
```
PS F:\github\typeormhana> hana-cli connect
Input: Connection String  <host>[:<port>]:  (node:17284) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
**********************************.hana.trial-eu10.hanacloud.ondemand.com:30041
Input: User:  aaaaaaaaa
Input: Password:  *************

Input: Encrypt connections (required for HANA As A Service or HANA Cloud):  t
Input: Optional: HDB User Store Key - Overrides all other Connection Parameters:
Input: SSL Trust Store:
-
Error: Connection Problem {}
    at dbConnect (D:\Programme\nvm\v15.5.0\node_modules\hana-cli\bin\connect.js:142:15)
```

**Comment by jung-thomas** [comment]
If you are using HANA Cloud Trial then the port is always 443.  In fact if you go to the SAP Cloud Platform Cockpit and choose Copy SQL Endpoint it will put the hostname and port into your clipboard
![image](https://user-images.githubusercontent.com/12159356/103220991-950d6a00-48ef-11eb-8c46-53b0b0fca261.png)
This is the value you would use in the connection string parameter.  
You would choose Encrypt connections as that is required for HANA As A Service and HANA Cloud (and I see from your hostname you are using HANA Cloud).  
You can choose to pass in an SSL Trust Store certificate if you don't have the trusted root certificate for HANA Cloud in your OS keychain already.  
The HDB User Store is an option parameter that allows you to store the connection parameters and credentials in an encrypted local secure store. https://help.sap.com/viewer/b3ee5778bc2e4a089d3299b82ec762a7/latest/en-US/dd95ac9dbb571014a7d7f0234d762fdb.html

**Comment by albertlast** [comment]
Thanks for the hint,
in the end in my case i got two issues.

First and most important use the wrong endpoint,
which i could fix with your information and
second issue is that i run nodejs 15.5.0 and not 12.20.

reason why i got ``Error: Connection Problem {}``
