### ISSUE TITLE
Add filename option for massConvert operation

### ISSUE THREAD

**Issue by ThePlenkov** [SAP-samples/hana-developer-cli-tool-example#25]
Hi @jung-thomas 

Thanks again for a tip to use massConvert command.

One more issue I would love to add -  is it possible to provide also filename as a parameter?

For example it could be useful for those who prefer to have all exported schemas in one folder. 

Thank you!

**Comment by ThePlenkov** [comment]
Created PR for that. Thanks

**Comment by jung-thomas** [comment]
Thank you for the contribution. I've merged it into the Main branch.  However It will probably be a day until I push the newly built version to npm. I have some other updates pending and I hope to due a big round of testing this afternoon before updating to npm.

**Comment by jung-thomas** [comment]
This feature is in the release that was just published to NPM - thanks.
