### ISSUE TITLE
DECIMAL type without decimals generates CDS error (inspectTable)

### ISSUE THREAD

**Issue by ThePlenkov** [SAP-samples/hana-developer-cli-tool-example#29]
Hi!

If we have a column like that
![image](https://user-images.githubusercontent.com/6381507/112483075-fb801800-8d78-11eb-9c5b-9243a2e33c47.png)

inpectTable gives us file like this:
![image](https://user-images.githubusercontent.com/6381507/112483230-1f435e00-8d79-11eb-9b07-ba9b4568fa8d.png)

I'll use same PR #28 to fix it

**Comment by ThePlenkov** [comment]
@jung-thomas  spec says scale is optional. What do you think to write better in this case `Decimal(34)` or `Decimal(34,0)`? Thanks

**Comment by ThePlenkov** [comment]
fixed in #28

**Comment by jung-thomas** [comment]
Confirmed fixed
