### ISSUE TITLE
Add pagination to the hdi and ups commands for environments with hundreds of service instances 😮

### ISSUE THREAD

**Issue by jung-thomas** [SAP-samples/hana-developer-cli-tool-example#40]

**Comment by jung-thomas** [comment]
@draschke - tagged as requestor. But please note it might be a few days before I have the bandwidth to look into this item

**Comment by jung-thomas** [comment]
I've upped the call page size to 5000 on the hdi and ups command. Should work for you now, although I don't have any environment that has that many services instances to test in. Fix will be in version 2.202105.5

**Comment by draschke** [comment]
Would check for it as soon npm for hana-cli is updated. [hana-cli hdi](https://github.com/draschke)

**Comment by jung-thomas** [comment]
New version is available in npm now
https://www.npmjs.com/package/hana-cli/v/2.202105.5

**Comment by draschke** [comment]
hana-cli status & hana-cli status -a are working. any idea?

**Connection Problems:  Error: Connection Problems:  {}**
```

PS C:\git\t3e\db> hana-cli hdi --cf false --debug
  hana-cli Yargs values: +0ms
  hana-cli {
  hana-cli   _: [ 'hdi' ],
  hana-cli   cf: false,
  hana-cli   c: false,
  hana-cli   cmd: false,
  hana-cli   debug: true,
  hana-cli   Debug: true,
  hana-cli   disableVerbose: false,
  hana-cli   quiet: false,
  hana-cli   'disable-verbose': false,
  hana-cli   '$0': 'hana-cli'
  hana-cli } +2ms
  hana-cli Prompt values: +4ms
  hana-cli { cf: false, disableVerbose: false, debug: true } +0ms
Connection Problems:  Error: Connection Problems:  {}
```

```
hana-cli: 2.202105.5
@sap/audit-logging: 5.0.0
@sap/cds: 5.1.4
@sap/cds-compiler: 2.2.8
@sap/cds-foss: 2.3.1
@sap/cds-runtime: 3.1.1
@sap/cds-dk: 4.1.4
@sap/cds-sidecar-client: 1.1.16
@sap/edm-converters: 1.0.41
@sap/eslint-plugin-cds: 1.1.3
@sap/hana-client: 2.8.20
@sap/hdbext: 7.2.0
@sap/e2e-trace: 3.0.0
@sap/textbundle: 4.0.0
@sap/xsenv: 3.1.0
@sap/xssec: 3.2.0
sap-hdbext-promisfied: 2.202105.1
```

**Comment by jung-thomas** [comment]
Are you logged in with the xs command from the command line?  That's the only way I can reproduce that message is if I don't login first with the xs.

**Comment by draschke** [comment]
no, I don't.

maybe I'm to tired for now. but it looks like a misspelling...**cf = require("../utils/xs")**

![image](https://user-images.githubusercontent.com/4199123/119053526-786cee00-b9c6-11eb-9241-3c9697ebe7fe.png)

**Comment by jung-thomas** [comment]
>no, I don't.

What do you mean by that? No you aren't logged in via xs login?

> but it looks like a misspelling...cf = require("../utils/xs")

No that's intentional. I created by the cf an xs libraries with the same interface.  That way I can have one check and load the specific implementation but keep all the other code working with the libraries the same.

**Comment by draschke** [comment]
I'm not logged in via xs login.

**Comment by draschke** [comment]
Thank you! It works if I'm logged in via xs. (Works only  via xs/cf because Its an xs/cf application construct.)

If I create a hdi-container via HANA-Cli there wont be a hdi-service created. Right?

**Comment by jung-thomas** [comment]
In this instance I'm just reusing the underlying xs/cf client.  I didn't want to duplicate the login/credentials handling/storing that xs/cf client is already doing.  Therefore I'm just using a child process to launch xs/cf and using the curl command to make requests to the xs/cf API. 
https://cli.cloudfoundry.org/en-US/v6/curl.html

So this does mean I'm basically just scripting calls through the xs/cf client and that you must already be logged in via the client before this command will work. However I wasn't happy with the error message in this situation. The true error details were getting lost in the call stack.  I've made an improvement to make sure those details will now surface up to the user:
![image](https://user-images.githubusercontent.com/12159356/119169016-8a36ab80-ba2f-11eb-92b4-2860aa64da9f.png)

**Comment by jung-thomas** [comment]
>If I create a hdi-container via HANA-Cli there wont be a hdi-service instance created. Right?

No they won't be there in the hana-cli hdi command. Because this command calls to the xs/cf APIs and only sees the service instances known there. 

Only the hana-cli containers command would show you the HDI containers created directly via SQL APIs as well.

**Comment by draschke** [comment]
> However I wasn't happy with the error message in this situation. The true error details were getting lost in the call stack. I've made an improvement to make sure those details will now surface up to the user:

Funny, when I was debugging it in the morning and saw this error msg, I thought the same. 😁 Thanks! Makes it much more easier!
