### ISSUE TITLE
Exclude user-defined table types from generated CDS (or support them as CDS types)

### ISSUE THREAD

**Issue by ThePlenkov** [SAP-samples/hana-developer-cli-tool-example#51]
Hi!

I just noticed that if we declare table type in the system like that:

![image](https://user-images.githubusercontent.com/6381507/119867856-a306fb80-bf1e-11eb-897f-c7e43150e835.png)

it ends up in CDS like this:
![image](https://user-images.githubusercontent.com/6381507/119868082-e5c8d380-bf1e-11eb-84c1-70306521469e.png)

if we'll try to select from such an entity - that will fail of course. 
![image](https://user-images.githubusercontent.com/6381507/119868287-24f72480-bf1f-11eb-9e65-1f0b9fb47320.png)

Therefore I propose for now just to exclude such user-defined types from the selection. And if needed to return the back already as CDS types.
Luckily we can simply filter out them with `IS_USER_DEFINED_TYPE = FALSE`

**Comment by jung-thomas** [comment]
Merged and delivered with 2.202105.9
