### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by greg2git** [SAP-samples/hana-developer-cli-tool-example#52]
Hi Tom,

i hope this is not a wrong entry point for my issue and maybe it can confirmed. if i want to use BTP to install binaries from scratch i think i may need _sudo_ , however if run it in my BTP dev space i get this error:
_bash: sudo: command not found_

when i put Azure to the side and try either Google or Amazon they both come back with
_usage: sudo -h | -K | -k | -V_

if there's a better place to raise this issue, please close it here and let me know where to try it next.

thank you,
greg

**Comment by jung-thomas** [comment]
Are you just talking about in general installing things into the Business Application Studio terminal/shell?

**Comment by greg2git** [comment]
yes, just getting as close to DIY as possible, if possible.

**Comment by jung-thomas** [comment]
We pretty intentionally don't give out the root privileges within the Business Application Studio environment. Do you have a specific tool/scenario you are trying to use that requires root?

**Comment by greg2git** [comment]
yes, install docker, docker-compose, go, and maybe few other tools. 

i heard they are pretty popular and i would like to use them alongside the latest HANA, if that makes any sense.

**Comment by jung-thomas** [comment]
We certainly support adding some command line utilities to BAS. Like hana-cli, jq, or others.  However what you are describing here are major new development workflows or programming runtimes.  SAP isn't focused on making BAS a general purpose Cloud IDE for all runtimes and scenarios but instead focuses on those mainline SAP specific tools and scenarios.  If Go or Docker become mainline to SAP development (which they might in the Kyma context down the road), then they should be validated and added to a dev workspace by SAP.
