### ISSUE TITLE
Error while creating HDI using CLi

### ISSUE THREAD

**Issue by satharva** [SAP-samples/hana-developer-cli-tool-example#55]
#53 
Thank you for making changes, I am able to connect to the database now.

Now I am not able to create a HDI Container using my Admin user. While debugging I found the following error:
![cli_issue_1](https://user-images.githubusercontent.com/77973707/122750529-40e6af80-d2ac-11eb-8e95-65ade2c7c7b7.jpg)
![cli_issue_2](https://user-images.githubusercontent.com/77973707/122750538-43e1a000-d2ac-11eb-9dc6-1242676e3097.jpg)
![cli_issue_3](https://user-images.githubusercontent.com/77973707/122750542-4512cd00-d2ac-11eb-96b6-8031105dd603.jpg)

**Comment by jung-thomas** [comment]
I see this is using the default-env-admin.json connection.  That's good.  What user did you setup to use in this case?  It needs to be something very powerful - like the SYSTEM user.  You are getting an insufficient privilege, so most likely something about this user doesn't have the rights to create the HDI Container.  If you take the GUID from the error message and pass it into the Stored Procedure SYS.GET_INSUFFICIENT_PRIVILEGE_ERROR_DETAILS - it will tell you exactly what is missing from the user.  You can also use the hana-cli command privilegeError https://github.com/SAP-samples/hana-developer-cli-tool-example#privilegeerror - but if the admin user doesn't have rights here it might also not have rights to lookup the privilege error. 

Those error details from the GUID are going to be critical to understanding what you user is missing and what needs to be added.

**Comment by satharva** [comment]
I have set up the Admin user of the database only. The admin user has been assigned all the roles and privileges. Is there some way we can give all the rights to the admin user?
I tried to look up using the hana-cli privilegeError but it says that ,"VError: Procedure SYS.GET_INSUFFICIENT_PRIVILEGE_ERROR_DETAILS does not exist" . 
Can I use this cli comman directly into the XSA server but downloading the latest version and all?

**Comment by jung-thomas** [comment]
Are you running the hana-cli privilegeError command as admin (with the -a command)?  It might be telling you that the procedure doesn't exist if you are actually running via an HDI container user.  Or a user that doesn't have privileges to even see this procedure. 

As the error message wit the guid is not produced by hana-cli but comes from HANA itself, it would seem odd that your system would produce the GUID but not have the procedure to read it.  What version of HANA are you running?  I tested in my HANA Express instance and the procedureError command works just fine:
![image](https://user-images.githubusercontent.com/12159356/122805354-ff97d500-d296-11eb-993a-51cce2bda1cd.png)

**Comment by satharva** [comment]
Yes I am using the -a command to see the privilege error. I am using HANA 2 SPS 04 Patch 6 ( Build 4.4.18 ).  I am trying to use it but I get the following error reply at the end:
![cli_issue](https://user-images.githubusercontent.com/77973707/122879008-05082480-d356-11eb-8b26-0e596ea9e5c4.jpg)

**Comment by jung-thomas** [comment]
I'm not exactly sure what to tell you. This procedure being missing in your system doesn't really make sense if you are on SPS 04.  It is listed in the help documentation for SPS 04: https://help.sap.com/viewer/b3ee5778bc2e4a089d3299b82ec762a7/2.0.04/en-US/9a73c4c017744288b8d6f3b9bc0db043.html?q=GET_INSUFFICIENT_PRIVILEGE_ERROR_DETAILS

Are you sure that's the same system you are connected to?  You use hana-cli systemInfo or hana-cli status to see some of the system details. 

But again it doesn't really make sense that you are getting the error GUID but then don't have the Procedure to look up that GUID.  SPS04 is the release that should have this procedure.  It is in the documentation.

**Comment by satharva** [comment]
I tried to put the "CALL SYS.GET_INSUFFICIENT_PRIVILEGE_ERROR_DETAILS" command but I was not able to get the details of the GUID error.
When I ran the hana-cli systemInfo -a command I got the following output.
![hana-cli](https://user-images.githubusercontent.com/77973707/123083848-204e5f00-d43e-11eb-8ffd-f18b88e2b531.jpg)

Is there some way I can give full privilege to the ADMIN user? I am also not understanding why the admin user is not having all privileges.

**Comment by jung-thomas** [comment]
So this is a HANA Express system.  Are you using the SYSTEM user for the admin connection?  SYSTEM should be powerful enough to get Privilege Error Details. Even your systemInfo call is returning insufficient privilege on the Statistics Alerts which would normally return fine with the SYSTEM user.

**Comment by satharva** [comment]
I have now tried it with the SYSTEM user and now I am not getting that insufficient privilege error.
Thank you for your help.
