### ISSUE TITLE
Error: Cannot find module 'fs/promises' in Node 12.x

### ISSUE THREAD

**Issue by jung-thomas** [SAP-samples/hana-developer-cli-tool-example#57]
Tool crashes with Error: Cannot find module 'fs/promises' when used in Node 12.x.  This is due to this feature being introduced in Node 10 but then removed in later patches for Node 10 and Node 12.  Works fine in Node 14. Node.js documentation was incorrectly listing this as supported in Node 12.  See https://github.com/nodejs/node/issues/35740

Will fix in hana-cli by changing to `require('fs').promises`

**Comment by AR-Student824** [comment]
F

**Comment by ericscottmarquez** [comment]
f

**Comment by DylanAlloy** [comment]
f

**Comment by beasteca** [comment]
f

**Comment by grasshopperL** [comment]
F

**Comment by Jorgcp99** [comment]
F

**Comment by zeromero-git** [comment]
f

**Comment by zhanilyasov** [comment]
F

**Comment by etkaar** [comment]
F

**Comment by elpideus** [comment]
F

**Comment by rteobaldo** [comment]
f

**Comment by wian-lloyd** [comment]
f

**Comment by danielwust** [comment]
F

**Comment by AugustoPreis** [comment]
F
