### ISSUE TITLE
Error: Connection failed (RTE:[89001] Cannot resolve host name

### ISSUE THREAD

**Issue by draschke** [SAP-samples/hana-developer-cli-tool-example#59]
I do get this error msg **"Cannot resolve host name"** sometimes, when running hana-cli commands.

To solve this issue I changed the default-env.json host value to the FQDN.
Maybe it would be better, to set the FQDN value when the env.json file is created?

In my case I had to change it, because the UI wasn't working. After I changed the host manually it worked.
Thanks for the new UI! Great work!

**Comment by jung-thomas** [comment]
I'm not sure what's happening here.  I've never encountered this.  It's of course the standard @sap/hana-client that is responsible for all communication including the host resolution. When you say maybe it would be better to set the FQDN, you just mean manually right?  Because the hana-cli takes either what you input for the host or pulls from the existing service instance key.  It never calculates any host names.  I'm not sure what I could do in this tool to improve the situation.

**Comment by draschke** [comment]
> I've never encountered this.

I think I encountered this issue also yesterday for the first time, but in more different situations while I was running hana-cli commands.

The default-env.json file was created by running the serviceKey command at first.

After changing the host from "tbase-qa" to "tbase-qa.company.de" the error msg disapeared.
In the CLI everything worked fine even with the error msg, it didn't bother me. But I had to change the host name for a successful running UI.

```
$ hana-cli tablesUI
HTTP Server: http://localhost:3010/ui/#tables-ui
Using Connection Configuration loaded via default-env.json 

Error: Connection failed (RTE:[89001] Cannot resolve host name 'tbase-qa' rc=-3: Temporary failure in name resolution (tbase-qa:30015))
```

**Comment by jung-thomas** [comment]
That's interesting.  I don't know what it would act differently from the UI.  The "backend" logic for sending queries to HANA is the same. I intentionally didn't want to have two copies of any logic that could get out of sync so I made sure the CLI and the UI both call the same thing. And really all the communication is happening from the same process, the only difference is if the output is sent to the console or put in an express response (or sent via Web Sockets). So I'm rather stumped as to why there was any difference in behavior or why adding the FQDN made a difference. And that RTE: [89001] -that's clearly an error coming from the @sap/hana-client itself.  I recognize the formatting.
