### ISSUE TITLE
Adopt remote Hana Cloud instance connect string

### ISSUE THREAD

**Issue by JayChanggithub** [SAP-samples/hana-developer-cli-tool-example#82]
Hi Support. 

I'd like to adopt this tool to implement operate Hana Cloud DB also when had been through BTP/CF create Hana instance ready. However how to replace "default-services.json"(Use remove hana instance information) in actually. ?

**Comment by jung-thomas** [comment]
I'm sorry but I don't really understand your issue. You want to replace the default-services.json? I don't know what you mean by that. Perhaps you could describe in detail what you are trying do or what is going wrong.

**Comment by JayChanggithub** [comment]
I just wanna to request have anything possible no  prompt to input password/username or any regarding that when i execute command. It's what i mean and also i go through documentation it will use default-admin-evn.json right? if so how to do can achieve my purpose?

**Comment by jung-thomas** [comment]
I'm sorry but I still really can't understand your request. Are you just asking if this tool can use the default-env.json? If so, yes that is exactly what it uses as described in the documentation:

https://github.com/SAP-samples/hana-developer-cli-tool-example#security

It can use the default-env.json, a .env or even .cdsrc-private.json.  You can create a default-env.json with the [connect](https://github.com/SAP-samples/hana-developer-cli-tool-example#connect) command or create one from a service binding with the [serviceKey](https://github.com/SAP-samples/hana-developer-cli-tool-example#servicekey) command.

**Comment by JayChanggithub** [comment]
@jung-thomas,

Yes. That's what I want to ask. Thank for your clarification.
