### ISSUE TITLE
flag in massConvert to exclude @cds.persistence.exists

### ISSUE THREAD

**Issue by mvmanov** [SAP-samples/hana-developer-cli-tool-example#84]
Hi,
 Since I am using the massConvert command to generate a cds from an XSC application and I want to actually create the tables in a new system based on CDS, not just generate proxies. I would appreciate if I have the option to exclude the @cds.persistence.exists annotation.

Thank you,
Milen

**Comment by jung-thomas** [comment]
Added new parameter useExists which defaults to true.  But if you set it to false the persistence exists annotation will not be placed in the output of the Inspect* commands and the massConvert.
