### ISSUE TITLE
hana-cli connection error

### ISSUE THREAD

**Issue by shahram** [SAP-samples/hana-developer-cli-tool-example#85]
Hi, @jung-thomas

I am having this issue with hana-cli:

Error: Could not connect to any host: [ xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.hana.trial-us10.hanacloud.ondemand.com:443 - Client network socket disconnected before secure TLS connection was establishe

Any idea?

Thx.

**Comment by jung-thomas** [comment]
Seems to be a connection issue.  Make sure your HANA Instance is running.  Remember it shuts down every night in trial/free tier accounts and manually has to be restarted.  Have you set the Allow IP addresses to all in the HANA Config?  Can you connect to this HANA database with any other tools (like CAP or hdbsql)?

**Comment by shahram** [comment]
It was "Allow all IP addresses". I just forgot to set it after creating a new HANA instance.

Thx.
