### ISSUE TITLE
Support default values during cds definition via massExport

### ISSUE THREAD

**Issue by mvmanov** [SAP-samples/hana-developer-cli-tool-example#87]
It would be beneficial to include information for default values in the generated cds via massExport command. E.g.
Entity ![....] {
key 	![matnr]: String(18)  @title: 'matnr' ; 
key 	![lifnr]: String(10)  @title: 'lifnr' ; 
key 	![werks]: String(4)  @title: 'werks' ; 
key 	![req_date]: String(8)  @title: 'req_date' ; 
key 	![modifId]: Integer  @title: 'modifId' ; 
key 	![version]: String(10)  @title: **'version' default ' '(currently not generated)**; 
	![prdha_1]: String(18)  @title: 'prdha_1' ; 
	![prdha_2]: String(18)  @title: 'prdha_2' ;

**Comment by jung-thomas** [comment]
Add at least experimental support for default values in latest release 3.202210.2
