### ISSUE TITLE
HANA / XSA logs to UI

### ISSUE THREAD

**Issue by ShockwaveConsulting** [SAP-samples/hana-developer-cli-tool-example#89]
while working on HANA XSA, it is very difficult to read the logs. Sometimes the error would display in the Web IDE console and sometimes it would refer to the cf mol -GUID something like that... so I would need to run the cf cli and download a log file - from there I have to read (cntrl F to find "error") it seems to be a very tedious process. I have not been able to find whether there is some nicer UI way to display the error logs either from the XSA cockpit or any other place. I hope we can collaborate to get the log command into your hana-cli. 

Thank you.

**Comment by jung-thomas** [comment]
Just getting back from vacation last week. I've got some priority items to do first for ASUG Dev Tools Days next week, but then I hope to have a closer look at this item later this week.

**Comment by ShockwaveConsulting** [comment]
Ok – Thank you.

***@***.***
Sergio Guerrero
President
469.230.8202
www.shockwaveconsulting.com<http://www.shockwaveconsulting.com/>
Follow me on the SAP Community<https://people.sap.com/sergio.guerrero#overview>
Let’s connect on LinkedIn<https://www.linkedin.com/in/sergio-guerrero-4ab84195/>
Ask me about Microservices in SAP HANA XSA<https://www.apress.com/us/book/9781484261170> or Fiori applications<https://www.apress.com/us/book/9781484263570>

**Comment by jung-thomas** [comment]
So I had a look at the xs logs command:

```
 xs help logs
xs command line client version v1.0.131

NAME:
   logs - Tail or show recent logs for an app

USAGE:
   Connect to tailing logs of an application:
   xs logs APP

   View all staging and access logs of an application:
   xs logs APP --all --source API,STG

   View recent ERR and OUT application logs of a specific instance:
   xs logs APP --recent --type ERR --type OUT --source APP --instance 0

ARGUMENTS:
   APP       The name of the app to show

OPTIONS:
   --recent                Dump recent logs instead of tailing
   --all                   Dump complete logs instead of tailing
   --last <NUM>            Show the last NUM lines of log for this instance.
   --since <TIMESPEC>      Show log lines since the specified time, which is either a time span (syntax: <x>[m|h|d]) or
                           a time stamp (expected format: yyyy-MM-dd HH:mm:ss).
   --till <TIMESPEC>       Show log lines till the specified time, which is a time stamp (expected format: yyyy-MM-dd
                           HH:mm:ss). The "since" and "till" options can be combined to define a time window, if the
                           "since value is also given in the time stamp format.
   --source <SOURCE>       Filter by the given log source (e.g. API, APP, STG or RTR). Option can be specified multiple
                           times.
   --type <TYPE>           Filter by the given log type (e.g. OUT, ERR, TRC, LOG, SYS or ACC). Option can be specified
                           multiple times.
   --instance <INSTANCE>   Filter by the given instance indice (e.g. 0 or 1). Option can be specified multiple times.
   --droplet <DROPLET>     Filter by the given droplet id (e.g. 0 or 1). Option can be specified multiple times.

SEE ALSO:
   app, apps, events, files
```

And cf logs:
```
 cf help logs
NAME:
   logs - Tail or show recent logs for an app

USAGE:
   cf.exe logs APP_NAME

OPTIONS:
   --recent      Dump recent logs instead of tailing

SEE ALSO:
   app, apps, ssh
```

Interestingly enough the xs logs command seems to be much more powerful.  Was your idea to bring some of these options to  CF as well?  Or was there something lacking in the xs logs command?  We have to look at the underlying API here though.  We can't really add anything that isn't in the REST API. 

Interesting conversation here: https://groups.google.com/a/cloudfoundry.org/g/vcap-dev/c/MzaQqvUyE64?pli=1

It would seem that CF is very light on log functionality itself.  The consensus is to use a third party logging and use it's query and analysis tools. It's not looking great that there is going to be anything in the underlying API that the hana-cli could use. 

If you have deeper needs here in the SAP BTP space there is the Application Logging service: https://discovery-center.cloud.sap/serviceCatalog/application-logging-service?region=all

**Comment by ShockwaveConsulting** [comment]
Thank you for your response, Tom.
Based on  your response, I see we should be using that 3rd party API and if more needs are required from the BTP, I will explore the Application Logging service.

Thank you again for your response.



***@***.***
Sergio Guerrero
President
469.230.8202
www.shockwaveconsulting.com<http://www.shockwaveconsulting.com/>
Follow me on the SAP Community<https://people.sap.com/sergio.guerrero#overview>
Let’s connect on LinkedIn<https://www.linkedin.com/in/sergio-guerrero-4ab84195/>
Ask me about Microservices in SAP HANA XSA<https://www.apress.com/us/book/9781484261170> or Fiori applications<https://www.apress.com/us/book/9781484263570>
