### ISSUE TITLE
Verification failed while extracting @sap/hana-client@2.5.86

### ISSUE THREAD

**Issue by lucodealethea** [SAP-samples/hana-developer-cli-tool-example#9]
Hi Thomas,

to successfully install hana-cli, I had to change the package-lock.json file

replacing integrity line such as after:

"@sap/hana-client": {
      "version": "2.5.86",
      "resolved": "https://npm.sap.com/@sap/hana-client/-/hana-client-2.5.86.tgz",
      "integrity": "sha512-Rk8WrhKSSFMrGWoOOT3tzYow3NdGZtSCMyDc06w3354fsUaaTyWZG9p/av5UTGCf9n1no1oa9X/HcSbhxwQGfQ==",
      "requires": {
        "debug": "3.1.0"
      },

otherwise, I would get :

npm WARN tarball tarball data for @sap/hana-client@2.5.86 (sha512-m1ECPz0OwqcmNtzB/Y92m3zuT+ePOI8Ypr9Z+GPtEHtJFCGgHYx8N/oaa/WGmA7xmwfNvDV9HLtasJnndewErw==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/hana-client@2.5.86 (sha512-m1ECPz0OwqcmNtzB/Y92m3zuT+ePOI8Ypr9Z+GPtEHtJFCGgHYx8N/oaa/WGmA7xmwfNvDV9HLtasJnndewErw==) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting @sap/hana-client@2.5.86:
npm ERR! Verification failed while extracting @sap/hana-client@2.5.86:
npm ERR! sha512-m1ECPz0OwqcmNtzB/Y92m3zuT+ePOI8Ypr9Z+GPtEHtJFCGgHYx8N/oaa/WGmA7xmwfNvDV9HLtasJnndewErw== integrity checksum failed when using sha512: wanted sha512-m1ECPz0OwqcmNtzB/Y92m3zuT+ePOI8Ypr9Z+GPtEHtJFCGgHYx8N/oaa/WGmA7xmwfNvDV9HLtasJnndewErw== but got sha512-Rk8WrhKSSFMrGWoOOT3tzYow3NdGZtSCMyDc06w3354fsUaaTyWZG9p/av5UTGCf9n1no1oa9X/HcSbhxwQGfQ==. (55293167 bytes)

This issue can then be closed

**Comment by jung-thomas** [comment]
I believe this is because you are still using the npm.sap.com registry. 

@sap Node.js packages have moved from https://npm.sap.com to the default registry https://registry.npmjs.org. As future versions of @sap modules are going to be published only there, please make sure to adjust your registry with:

npm config delete @sap:registry

**Comment by jung-thomas** [comment]
Although I see the package-lock.json suprising has some references to npm.sap.com still in it.  I'm not sure why as I've pushed since switching to the main registry myself.  Let me look into that real quick. For interest; what registry are you configured to use (can do a npm config list to see).

**Comment by lucodealethea** [comment]
Ok Thomas, 

npm config list -l
; cli configs
long = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.13.4 node/v12.16.0 linux x64"

; userconfig /home/xxxhana/.npmrc
@sap:registry = "https://registry.npmjs.org/"

; default values

**Comment by jung-thomas** [comment]
Ok sorry about that.  Definitely on my side.  It was the package-lock.json still having npm.sap.com entries in it. But just pushed and corrected that. Should be all good now. Thanks!
