### ISSUE TITLE
[ERROR]  No service key "undefined" found for service instance "xx-db"

### ISSUE THREAD

**Issue by rgadirov** [SAP-samples/hana-developer-cli-tool-example#93]
Hi @jung-thomas 

when executing npm run hana, I get the following error. 
Retrieving data from Cloud Foundry... 
[ERROR] No service key "undefined" found for service instance "cv-db".

This wasn´t the case weeks ago,
I also specified the key of my instance via command:
hana-cli serviceKey [instance] [key]

Maybe you have any idea?

Thank you.

BR
Rufat

**Comment by jung-thomas** [comment]
What is `npm run hana`? There is no such npm script in this repository. I assume this is from your own project. You are using hana-cli serviceKey to create the default-env.json I take it.  But I don't see how else this is related to hana-cli.

**Comment by rgadirov** [comment]
HI @jung-thomas 

yes, you are right, it is my own script:  "hana": "cds deploy --to hana:cv-db --auto-undeploy"
I thought the error was related to hana-cli. Now, I think it is not, more to deployment process. Sorry for the confusion.

BR
Rufat
