### ISSUE TITLE
HANA-CLI Tables not working

### ISSUE THREAD

**Issue by romi9035** [SAP-samples/hana-developer-cli-tool-example#96]
Hello,

I am getting below error while executing HANA-CLI Tables command. Screenshot is also attached.

TypeError: require(...).resolver is not a function

![HANA-CLi Tables](https://user-images.githubusercontent.com/47141660/217283234-58b4c39a-6966-44aa-b293-712734376b16.PNG)

Regards,
Romil A.

**Comment by jung-thomas** [comment]
Sorry about that.  Doesn't appear to be a completely general issue as I'm able to issue the tables command and it returns correctly
![image](https://user-images.githubusercontent.com/12159356/217306099-df559ecc-7519-4ba3-9d74-b4380a93f73a.png)

Which means I need to know a little bit more about your situation to troubleshoot.  Could you issue this same command with the --debug flag and share the detailed output there?

```hana-cli tables --debug```

There will be lots of output, but this will really help me determine what's triggering this error in your case.  Just if you post the results of that output be sure to block out sensitive information. The debug log will also list details like connection passwords and certificates. I'm mostly looking for the triggering flow of this error.

**Comment by jung-thomas** [comment]
I've found the error. It only occured when using the `cds bind` connection infomation.  The CDS Development Kit module that we are using for the lookup has changed structure slightly.  I have adjusted the hana-cli accordingly and published a new version, 3.202302.2, to npm with this fix.

**Comment by romi9035** [comment]
Thank you, Thomas. It is working now

Regards,
Romil A.
