### ISSUE TITLE
CF create-service xsuaa not able to read xs-security.json file

### ISSUE THREAD

**Issue by romi9035** [SAP-samples/hana-developer-cli-tool-example#97]
Hello,

I am getting below error while creating XSUAA service instance using xs-security.json file.
![image](https://user-images.githubusercontent.com/47141660/217610173-cfab64e8-b339-48f7-b5b3-3b026947cdae.png)

Without using  -c xs-security.json file , service instance is getting created.

![image](https://user-images.githubusercontent.com/47141660/217610722-cb86ad95-883d-4c6e-9226-2ed015bb66d5.png)

Regards,
Romil A.

**Comment by jung-thomas** [comment]
I don't see what this issue has to do with the hana-cli tool.   That said I think you would need to say -c .\xs-security.json for the cf command to know that you are giving it a file path.
