### ISSUE TITLE
convert to hdbview

### ISSUE THREAD

**Issue by karthicktsb** [SAP-samples/hana-developer-cli-tool-example#99]
Hi Thomas,

I can see there is massconvert for converting hdbdd entities to hdbtable format. But it does not convert views to hdbview format.

Do you have plan to support this request.

currently i am migrating from Neo to CF. There are 100 of views to converted to hdbview files.

Still i used the inspectview option to convert view to hdbview for the below view

context MD_SPC {
	view TEMP as select from c {
		MO, MATERIALNR, UOM, CURRENCY, MAX(CALMONTH) CALMONTH
	}
	where ID_DATASET = 1
	GROUP BY MO, MATERIALNR, UOM, CURRENCY;
	
	view VIEW as select from c join TEMP as z on c.MO=z.MO and c.UOM = z.UOM and c.CURRENCY = z.CURRENCY and c.MATERIALNR = z.MATERIALNR and c.CALMONTH = z.CALMONTH {
		c.MO,
		c.CURRENCY,
		c.MATERIALNR,
		max(c.COSTPERUOM) COSTPERUOM
		//c.COSTPERPIECE
	}//where c.UOM = 'ST'
	GROUP BY c.MO, c.MATERIALNR, c.CURRENCY;	
};

hana-cli inspectView HFP_INTERNAL HFP_PMT.VIEW::MD_SPC.VIEW -o hdbview -a
Using Connection Configuration loaded via default-env-admin.json

CDS compilation failed
<stdin>.cds:1:21-22: Error: Extraneous ‘:’, expecting ‹Identifier›
<stdin>.cds:1:22-33: Error: No artifact has been found with name “MD_SPC_VIEW” (in entity:“HFP_PMT_VIEW”)

Is there any way i can convert to hdbview format or similar? please let me know can you please suggest if there is any option exists.

Regards,
Karthick

Regards,
Karthick

**Comment by jung-thomas** [comment]
There are no current plans to add views to the Mass Convert. That would be an enhancement request.

As far as the inspectView - are you using the name of the object within the database?  You can't use the CDS name but the SQL View name.  We lookup by the SQLView name.  If that is your SQLView name then you likely need the --useQuoted true parameter on the command.

**Comment by jung-thomas** [comment]
I have added Views to massConvert with the latest release this afternoon.
